strategy_family: VTM_VOL_MR
enable_strategy_v3: false

max_trades_per_day: 2
cooldown_after_trade_bars: 2

trend_sessions:
  - "00:00-23:59"
range_sessions:
  - "00:00-23:59"
blocked_windows:
  - "21:50-22:10"

vtm_vol_mr:
  signal_model: shock_session
  atr_period: 14
  ma_period: 30
  shock_threshold: 3.0
  stop_atr: 1.0
  target_atr: 1.2
  holding_bars: 8
  close_extreme_pct: 0.10
  close_extreme_frac: 0.10
  entry_windows_utc:
    - "07:00-08:00"
  excluded_windows: []
  spread_max_usd: 1.0
  be_trigger_atr: 0.0

spread_usd: 0.41
slippage_usd: 0.05
progress_every_days: 30

