strategy_family: VTM_VOL_MR
enable_strategy_v3: false

vtm_vol_mr:
  atr_period: 10
  ma_period: 20
  threshold_range: 1.5
  stop_atr: 0.8
  holding_bars: 4
  close_extreme_frac: 0.10
  vol_filter_min: 0.8
  slope_lookback: 8
  slope_threshold: 0.0
  spread_max_usd: 1.0
  exit_on_sma_cross: true
  be_trigger_atr: 0.4
  entry_windows:
    - "00:30-22:30"
  excluded_windows:
    - "21:30-22:30"

max_trades_per_day: 4
cooldown_after_trade_bars: 0

spread_usd: 0.41
slippage_usd: 0.05
progress_every_days: 30
