strategy_family: VTM_VOL_MR
enable_strategy_v3: false

vtm_vol_mr:
  atr_period: 20
  ma_period: 40
  threshold_range: 2.2
  stop_atr: 1.2
  holding_bars: 8
  close_extreme_frac: 0.12
  vol_filter_min: 1.1
  slope_lookback: 12
  slope_threshold: 0.08
  spread_max_usd: 0.8
  exit_on_sma_cross: true
  be_trigger_atr: 0.7
  entry_windows:
    - "01:00-21:00"
  excluded_windows:
    - "07:30-08:30"
    - "12:30-13:30"
    - "16:30-17:30"
    - "21:30-22:30"

max_trades_per_day: 2
cooldown_after_trade_bars: 2

spread_usd: 0.41
slippage_usd: 0.05
progress_every_days: 30
